--QUERY UMA TABELA
SELECT * FROM SC5990 WHERE D_E_L_E_T_ <> '*'



--QUERY DUAS OU MAIS TABELAS
--INNER JOIN - O QUE TEM NAS DUAS TABELAS
--LEFT JOIN - TEM QUE TER NA ESQUERDA E NAO NECESSARIAMENTE NA DIREITA (SC5990 E N�O NECESSARIAMENTE NA SC6990)
--RIGHT JOIN - TEM QUE TER NA DIREITA E NAO NECESSARIAMENTE NA ESQUERDA (SC6990 E N�O NECESSARIAMENTE NA SC5990)

SELECT * FROM SC5990 C5 
INNER JOIN SC6990 C6 ON C6_FILIAL = C5_FILIAL AND C6_NUM = C5_NUM AND C6.D_E_L_E_T_ <> '*'
INNER JOIN SF4990 F4 ON F4_CODIGO = C6_TES AND F4_FILIAL = C6_FILIAL AND F4.D_E_L_E_T_ <> '*'
WHERE
C5.D_E_L_E_T_ <> '*'

SELECT * FROM SC5990 C5 
LEFT JOIN SC6990 C6 ON C6_FILIAL = C5_FILIAL AND C6_NUM = C5_NUM AND C6.D_E_L_E_T_ <> '*'


--QUERY COLUNAS
SELECT C5_NUM, C5_EMISSAO FROM SC5990 WHERE D_E_L_E_T_ <> '*'

--ORDENACAO QUERY
SELECT * FROM SC5990 ORDER BY C5_PESOL  DESC

--AGRUPAMENTO

--TRAZENDO QUANTIDADE DE REGISTROS
SELECT COUNT(*) CONTADOR FROM SC5990 WHERE D_E_L_E_T_ <> '*' ORDER BY CONTADOR

--AVG (m�dia)
SELECT C6_PRCVEN, AVG(C6_QTDVEN) MEDIA FROM SC6990 GROUP BY C6_PRCVEN

--MAX (m�ximo)
SELECT MAX(C6_QTDVEN) FROM SC6990 
SELECT MAX(C5_EMISSAO) FROM SC5990 

--MIN (m�nimo)
SELECT MIN(C6_QTDVEN) FROM SC6990 

--SUM (somar)
SELECT SUM(C6_QTDVEN) TOTAL_ITENS FROM SC6990 


--OPERADORES
--  +, - , * , / , %

-- MATEMATICO
SELECT C6_QTDVEN,C6_QTDVEN  FROM SC6990 

--CONCATENACAO
SELECT RTRIM(A1_END)+' ,'+A1_COD FROM SA1990 WHERE D_E_L_E_T_ <> '*'

--COMPARACAO
-- >, <, >=, <= ,!>, !<, !=, <>, =
SELECT * FROM SA1990 WHERE D_E_L_E_T_ <> '*' AND A1_COD >= '000002'

--COMPARACAO UMA LISTA - IN
SELECT * FROM SA1990 WHERE D_E_L_E_T_ <> '*' AND A1_COD IN ('000002','000004','000006')

--COMPARAR ENTRE VALORES - BETWEEN
SELECT * FROM SA1990 WHERE D_E_L_E_T_ <> '*' AND A1_COD BETWEEN '000002' AND '000006'


--COMPARAR PARTES - LIKE
SELECT * FROM SA1990 WHERE D_E_L_E_T_ <> '*' AND A1_NOME LIKE '%DE%'


-- INVERTER UMA CONDICAO - NOT
SELECT * FROM SA1990 WHERE D_E_L_E_T_ <> '*' AND A1_COD NOT IN ('000002','000004','000006')
SELECT * FROM SA1990 WHERE D_E_L_E_T_ <> '*' AND A1_NOME NOT LIKE '%DE%'

-- GROUP BY
SELECT COUNT(*), A1_PESSOA FROM SA1990 WHERE D_E_L_E_T_ <> '*' GROUP BY A1_PESSOA 
SELECT COUNT(*) FROM SA1990 WHERE D_E_L_E_T_ <> '*' AND A1_PESSOA = 'J'

-- HAVING
SELECT
COUNT(*) AS QTD, A1_FILIAL, LEFT(A1_NOME,4) FROM SA1990 WHERE
D_E_L_E_T_ <> '*' 
GROUP BY A1_FILIAL, LEFT(A1_NOME,4)
HAVING COUNT(*) > 1


-- UNION
SELECT A1_FILIAL, A1_COD, A1_MAIDUPL FROM SA1990 WHERE D_E_L_E_T_ <> '*' AND A1_NOME LIKE 'TESTE%'
UNION
SELECT A1_FILIAL, A1_COD, A1_MAIDUPL FROM SA1990 WHERE D_E_L_E_T_ <> '*' AND A1_NOME NOT LIKE 'TESTE%'




